// ════════════════════════════════════════════════════════════════
// VCT PLATFORM — Federation Feature Barrel Export
// ════════════════════════════════════════════════════════════════

export { Page_federation_provinces } from './Page_federation_provinces'
export { Page_federation_org_chart } from './Page_federation_org_chart'
export { Page_federation_documents } from './Page_federation_documents'
export { Page_federation_discipline } from './Page_federation_discipline'
export { Page_federation_certifications } from './Page_federation_certifications'
export { Page_federation_approvals } from './Page_federation_approvals'
export { Page_provincial_dashboard } from './Page_provincial_dashboard'
export { Page_discipline_dashboard } from './Page_discipline_dashboard'
export { Page_approval_detail } from './Page_approval_detail'
export { Page_workflow_config } from './Page_workflow_config'
export { Page_international_relations } from './Page_international_relations'
export { Page_pr_communications } from './Page_pr_communications'
export { Page_cert_verification } from './Page_cert_verification'
export { Page_executive_dashboard } from './Page_executive_dashboard'
export { Page_pending_approvals } from './Page_pending_approvals'
export { Page_submit_approval } from './Page_submit_approval'
export { Page_federation_organizations } from './Page_federation_organizations'
export { Page_federation_master_data } from './Page_federation_master_data'
export { Page_federation_finance } from './Page_federation_finance'
export { Page_federation_regulations } from './Page_federation_regulations'
export { Page_province_clubs } from './Page_province_clubs'
export { Page_province_athletes } from './Page_province_athletes'
export { Page_province_coaches } from './Page_province_coaches'
export { Page_province_tournaments } from './Page_province_tournaments'
export { Page_province_reports } from './Page_province_reports'
export { Page_federation_dashboard } from './Page_federation_dashboard'
export { Page_federation_personnel } from './Page_federation_personnel'
export { Page_federation_workflow_config } from './Page_federation_workflow_config'
export { Page_federation_international } from './Page_federation_international'
export { Page_federation_pr } from './Page_federation_pr'

// ── New pages (restructuring) ──
export { Page_federation_calendar } from './Page_federation_calendar'
export { Page_federation_invoices } from './Page_federation_invoices'
export { Page_federation_fees } from './Page_federation_fees'
export { Page_federation_sponsorship } from './Page_federation_sponsorship'
export { Page_federation_budget } from './Page_federation_budget'
export { Page_federation_notifications } from './Page_federation_notifications'

