// Mobile services and platform-facing utilities.

export { apiClient } from '../api-client'
export { CircuitBreaker, RetryWithBackoff } from '../api-resilience'
export { createApiVersionInterceptor } from '../api-version-interceptor'
export { bootstrapApp } from '../app-bootstrap'
export { VCTApp, MainStackNavigator } from '../app-entry'
export { AppWrapper } from '../app-wrapper'
export { authStorage } from '../auth-storage'
export { configManager } from '../config-manager'
export { crashReporter } from '../crash-reporter'
export { registerDeepLinks, buildDeepLink, buildUniversalLink } from '../deep-linking'
export { deviceInfo } from '../device-info'
export { featureFlags } from '../feature-flags'
export { imageCache } from '../image-cache'
export { createInterceptorChain } from '../interceptor-chain'
export { requestLogger } from '../request-logger'
export { secureStorage } from '../secure-storage'
export { sslPinning } from '../ssl-pinning'
export { WebSocketClient } from '../websocket-client'
export { backgroundTaskManager } from '../background-tasks'
export { performanceMonitor, usePerformanceMonitor, markAppStart, getTimeSinceStart } from '../performance-monitor'
export { analyticsTracker } from '../analytics-tracker'
export { appLifecycle } from '../app-lifecycle'
export { accessibilityHelpers } from '../accessibility-helpers'
export { triggerHaptic } from '../haptic-feedback'
export { securityUtils } from '../security-utils'
export { biometrics } from '../biometrics-auth'
export { permissionManager } from '../permission-manager'
